channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- matplotlib=2.2.2
- numpy=1.14.5
- pandas=0.23.1
- scipy=1.1.0
- seaborn=0.8.1
- jupyter=1.0.0
- notebook=5.5.0
- ipykernel=4.8.2
- dask=0.18.0
- numcodecs=0.5.5
- zarr=2.2.0
- scikit-allel=1.1.10
- perf=1.5.1

